### ISSUE TITLE
use wrangler version from package.json

### ISSUE THREAD

**Issue by wydengyre** [cloudflare/wrangler-action#231]
It should be possible to tell the action to get the wrangler version from `package.json` dependencies. I'd even say that is sensible default behavior.

**Comment by ludeeus** [comment]
As a workaround for that, you can read it in a step and reuse that value with something like this:

```yaml
...
      - name: Set wrangler version
        id: wrangler
        run: echo "version=$(jq -r .devDependencies.wrangler package.json | cut -c2-)" >> "$GITHUB_OUTPUT"
...
      - name: Build something awesome
        uses: cloudflare/wrangler-action@v3.4.1
        with:
          ...
          wranglerVersion: ${{ steps.wrangler.outputs.version }}
```

**Comment by AdiRishi** [comment]
This issue is resolved as of `cloudflare/wrangler-action@v3.6.0`.

**Comment by TonyRL** [comment]
This issue is back as of `cloudflare/wrangler-action@v3.6.1`.
