### ISSUE TITLE
Support version preview urls in Cloudflare workers

### ISSUE THREAD

**Issue by Phoenixmatrix** [cloudflare/wrangler-action#302]
Cloudflare Workers now support preview urls similar to Cloudflare Pages. Unfortunately wrangler's output for those is slightly different than the output from Pages, so the regex doesn't catch it to store in deployment-url.

Example of Wrangler's output:

Version Preview URL: https://an21s8iyi-worker-test.mydomain.workers.dev/

Without that, it's difficult to get access to the url in a version preview (it's available in the output, but its tough to capture it to use elsewhere in my GitHub action).

**Comment by nprogers** [comment]
We can pull this from wrangler artifacts.

**Comment by Meai** [comment]
btw it seems like preview urls are not correctly disabled on deploy even though I've specified workers_dev = false as described here in the docs: [preview url docs](https://developers.cloudflare.com/workers/configuration/previews/#making-preview-urls-inaccessible)
It only disables the worker.dev url, not the preview url. I'm not sure where to report this.

**Comment by crzidea** [comment]
> btw it seems like preview urls are not correctly disabled on deploy even though I've specified workers_dev = false as described here in the docs: [preview url docs](https://developers.cloudflare.com/workers/configuration/previews/#making-preview-urls-inaccessible) It only disables the worker.dev url, not the preview url. I'm not sure where to report this.

Also met the problem here.

**Comment by rimmer** [comment]
https://github.com/cloudflare/workers-sdk/pull/7243 has been merged, isn't it time to unlock this one?

**Comment by RowenTey** [comment]
Any updates on this issue? Would love this feature!

**Comment by crzidea** [comment]
> Any updates on this issue? Would love this feature!

@RowenTey I am sure this issue has been solved, and the document has been updated.

[https://developers.cloudflare.com/workers/configuration/previews/#disabling-preview-urls-in-the-wrangler-configuration-file](https://developers.cloudflare.com/workers/configuration/previews/#disabling-preview-urls-in-the-wrangler-configuration-file)

**Comment by RowenTey** [comment]
> > Any updates on this issue? Would love this feature!
> 
> [@RowenTey](https://github.com/RowenTey) I am sure this issue has been solved, and the document has been updated.
> 
> https://developers.cloudflare.com/workers/configuration/previews/#disabling-preview-urls-in-the-wrangler-configuration-file

Yep sorry, just tested it out and got it to work!

**Comment by steebchen** [comment]
The original issue is still relevant, is there any progress? It would be great to have this to have previews for workers

**Comment by BPreisner** [comment]
@nprogers @jahands I would truly appreciate any update on this issue 💯

**Comment by MatteoGauthier** [comment]
Hey, is there any 2026 news ? This is blocking me from using Workers instead of Pages

**Comment by suhailskhan** [comment]
There is a another feature that wrangler-action has which similarly only supports Pages and not Workers:

-  #377 

I was involved in a project whose CI/CD needed the functionality called for by both this issue and the one above, so I made a fork of this action, and IIRC I implemented both. I would not suggest using this in your workflows, but here it is:

[suhailskhan/wrangler-action](https://github.com/suhailskhan/wrangler-action)

It was a quick and dirty patch and not necessarily worthy of being merged to upstream, so I left it to be for just for my own purposes. I could, however, rework and/or polish it up for a PR.
